name: Build Documents

on:
  push:
    paths:
      - 'markdown/**'
      - 'templates/pandoc/**'
      - 'scripts/**'
      - 'source/**'
      - 'pandoc.yaml'
  pull_request:
    paths:
      - 'markdown/**'
      - 'templates/pandoc/**'
      - 'scripts/**'
      - 'source/**'
      - 'pandoc.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate repo
        run: |
          bash scripts/validate_repo.sh

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc and TeX (XeLaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 'v0.13.1'

      - name: Build documents
        run: |
          bash scripts/build_pandoc.sh

      - name: Upload artifacts (PDF)
        uses: actions/upload-artifact@v4
        with:
          name: pdf-artifacts
          path: pdf/

      - name: Upload artifacts (LaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: latex-artifacts
          path: latex/

      - name: Upload artifacts (DOCX)
        uses: actions/upload-artifact@v4
        with:
          name: docx-artifacts
          path: docx/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build HTML
        run: bash scripts/generate_html_index.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
